import { TherapistCard } from '@/types/therapist';

export const VERIFIED_THERAPISTS_CATALOG: TherapistCard[] = [
  {
    id: 'th-1',
    slug: 'dr-kajal-vora',
    name: 'Dr. Kajal Vora, PT',
    qualification: 'MPT (Neurology), BPT, MIAP',
    specialization: 'Neurology',
    experience: '12 Years',
    city: 'Mumbai',
    state: 'Maharashtra',
    areas: ['Colaba', 'Cuffe Parade', 'Marine Drive', 'Worli', 'Bandra West', 'Lower Parel'],
    rating: 4.9,
    reviewCount: 128,
    imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
    languages: ['English', 'Hindi', 'Gujarati', 'Marathi'],
    services: ['Neuro Rehabilitation', 'Stroke Recovery', 'Parkinson Care', 'Geriatric Rehab'],
    bio: 'Senior consultant neuro-physiotherapist with over 12 years of clinical experience in home-based stroke recovery, neuromuscular facilitation, and post-brain trauma functional restoration.',
    isVerified: true,
    education: ['Master of Physiotherapy (Neurology) - MUHS', 'Bachelor of Physiotherapy - KEM Hospital Mumbai'],
    feedback: [
      { rating: 5, comment: 'Dr. Kajal transformed my father recovery after stroke. Extremely patient and competent.', user: 'Rohan Mehta' },
      { rating: 5, comment: 'Remarkable improvement in mobility within 3 weeks of home visits.', user: 'Ananya S.' },
    ],
  },
  {
    id: 'th-2',
    slug: 'dr-twinkle-patel',
    name: 'Dr. Twinkle Patel, PT',
    qualification: 'BPT, MIAP, Certified Manual Therapist',
    specialization: 'Orthopedics',
    experience: '10 Years',
    city: 'Mumbai',
    state: 'Maharashtra',
    areas: ['Andheri West', 'Lokhandwala', 'Juhu', 'Powai', 'Goregaon', 'Bandra East'],
    rating: 4.8,
    reviewCount: 96,
    imageUrl: 'https://images.unsplash.com/photo-1594824813686-45543d3b76cf?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
    languages: ['English', 'Hindi', 'Gujarati'],
    services: ['Orthopedic Rehab', 'Spine & Joint Mobilization', 'Frozen Shoulder', 'Knee Replacement Care'],
    bio: 'Specialist in orthopedic rehabilitation and biomechanical alignment, focusing on rapid pain relief and long-term functional stability for joint and spine conditions.',
    isVerified: true,
    education: ['Bachelor of Physiotherapy - DY Patil Medical College', 'Certification in Mulligan Concept & Dry Needling'],
    feedback: [
      { rating: 5, comment: 'Relieved my severe frozen shoulder pain when other treatments failed.', user: 'Kavita Desai' },
    ],
  },
  {
    id: 'th-3',
    slug: 'dr-sam-evans',
    name: 'Dr. Sam Evans, PT',
    qualification: 'MPT (Sports Medicine), CSCS',
    specialization: 'Sports',
    experience: '15 Years',
    city: 'Delhi',
    state: 'Delhi',
    areas: ['South Delhi', 'Vasant Vihar', 'Greater Kailash', 'Golf Course Road', 'Gurugram', 'Cyber City'],
    rating: 4.9,
    reviewCount: 142,
    imageUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
    languages: ['English', 'Hindi', 'Punjabi'],
    services: ['Sports Injury Rehab', 'ACL/Meniscus Recovery', 'Athletic Performance', 'Dry Needling'],
    bio: 'Senior sports physiotherapist and certified strength & conditioning specialist with experience managing athletes and post-operative orthopedic recovery.',
    isVerified: true,
    education: ['MPT (Sports Physiotherapy) - Jamia Hamdard', 'Certified Strength & Conditioning Specialist (NSCA)'],
    feedback: [
      { rating: 5, comment: 'Helped me get back to running after my ACL surgery. Truly top-class guidance.', user: 'Vikram Grover' },
    ],
  },
  {
    id: 'th-4',
    slug: 'dr-chloe-davis',
    name: 'Dr. Chloe Davis, PT',
    qualification: 'MPT (Musculoskeletal Disorders)',
    specialization: 'Pain Management',
    experience: '8 Years',
    city: 'Bengaluru',
    state: 'Karnataka',
    areas: ['Indiranagar', 'Koramangala', 'HSR Layout', 'Whitefield', 'Bellandur', 'Sadashivanagar'],
    rating: 4.9,
    reviewCount: 84,
    imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
    languages: ['English', 'Kannada', 'Hindi'],
    services: ['Chronic Pain Management', 'Ergonomic Posture Correction', 'Spine Rehabilitation', 'Myofascial Release'],
    bio: 'Musculoskeletal specialist dedicated to non-invasive pain management, spinal posture correction, and evidence-based home recovery protocols.',
    isVerified: true,
    education: ['MPT (Musculoskeletal) - Manipal Academy of Higher Education'],
    feedback: [
      { rating: 5, comment: 'Excellent ergonomic and posture coaching. My chronic back pain is completely gone.', user: 'Siddharth Rao' },
    ],
  },
  {
    id: 'th-5',
    slug: 'dr-rajesh-sharma',
    name: 'Dr. Rajesh Sharma, PT',
    qualification: 'MPT (Cardio-Respiratory & ICU Rehab)',
    specialization: 'Geriatrics',
    experience: '14 Years',
    city: 'Pune',
    state: 'Maharashtra',
    areas: ['Koregaon Park', 'Baner', 'Aundh', 'Viman Nagar', 'Kothrud', 'Kalyani Nagar'],
    rating: 4.9,
    reviewCount: 110,
    imageUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
    languages: ['English', 'Marathi', 'Hindi'],
    services: ['Elderly Fall Prevention', 'Cardio-Pulmonary Rehab', 'Post-Op Mobility', 'Balance Training'],
    bio: 'Dedicated senior physical therapist specializing in geriatric mobility, pulmonary rehabilitation, and customized fall prevention routines for elderly patients.',
    isVerified: true,
    education: ['MPT (Cardiorespiratory) - Sancheti Institute of Orthopaedics and Rehabilitation'],
    feedback: [
      { rating: 5, comment: 'Dr. Rajesh was so gentle and encouraging with my 82-year-old mother. Highly recommended.', user: 'Pooja Kulkarni' },
    ],
  },
  {
    id: 'th-6',
    slug: 'dr-ananya-roy',
    name: 'Dr. Ananya Roy, PT',
    qualification: 'MPT (Pediatric Physiotherapy)',
    specialization: 'Pediatrics',
    experience: '9 Years',
    city: 'Kolkata',
    state: 'West Bengal',
    areas: ['Salt Lake', 'Alipore', 'New Town', 'Ballygunge', 'Park Street', 'Rajarhat'],
    rating: 4.8,
    reviewCount: 78,
    imageUrl: 'https://images.unsplash.com/photo-1594824813686-45543d3b76cf?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
    languages: ['English', 'Bengali', 'Hindi'],
    services: ['Pediatric Neuro Development', 'Cerebral Palsy Therapy', 'Developmental Delay Care', 'Sensory Integration'],
    bio: 'Child development and pediatric physiotherapy expert passionate about helping infants and young children achieve crucial physical milestones in a comforting home environment.',
    isVerified: true,
    education: ['MPT (Pediatrics) - National Institute for the Orthopaedically Handicapped'],
    feedback: [
      { rating: 5, comment: 'Incredible patience and play-therapy techniques for our 5-year-old.', user: 'Debashish Sen' },
    ],
  },
  {
    id: 'th-7',
    slug: 'dr-vikramaditya-reddy',
    name: 'Dr. Vikramaditya Reddy, PT',
    qualification: 'MPT (Orthopedics & Sports Rehab)',
    specialization: 'Orthopedics',
    experience: '11 Years',
    city: 'Hyderabad',
    state: 'Telangana',
    areas: ['Jubilee Hills', 'Banjara Hills', 'Gachibowli', 'HITEC City', 'Madhapur', 'Kondapur'],
    rating: 4.9,
    reviewCount: 105,
    imageUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
    languages: ['English', 'Telugu', 'Hindi'],
    services: ['Knee & Hip Rehabilitation', 'Post-Trauma Ortho Rehab', 'Spine Mobilization', 'Sports Injury Recovery'],
    bio: 'Orthopedic clinical specialist with deep expertise in advanced electrotherapy modalities, joint mobilization, and post-trauma recovery.',
    isVerified: true,
    education: ['MPT (Orthopedics) - Nizam Institute of Medical Sciences'],
    feedback: [
      { rating: 5, comment: 'Fast and comprehensive knee rehabilitation following arthroscopy.', user: 'Srinivas V.' },
    ],
  },
  {
    id: 'th-8',
    slug: 'dr-priya-sundaram',
    name: 'Dr. Priya Sundaram, PT',
    qualification: 'BPT, MPT (Women Health), CMP',
    specialization: "Women's Health",
    experience: '13 Years',
    city: 'Chennai',
    state: 'Tamil Nadu',
    areas: ['Anna Nagar', 'Adyar', 'Boat Club', 'OMR', 'Nungambakkam', 'Besant Nagar'],
    rating: 4.9,
    reviewCount: 115,
    imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
    languages: ['English', 'Tamil', 'Hindi'],
    services: ['Pre & Post Natal Care', 'Pelvic Floor Therapy', 'Diastasis Recti Repair', 'Core Strengthening'],
    bio: 'Women health and pelvic rehabilitation consultant offering compassionate and evidence-grounded care for prenatal comfort and postpartum physical restoration.',
    isVerified: true,
    education: ['MPT (Women Health) - Sri Ramachandra Institute of Higher Education'],
    feedback: [
      { rating: 5, comment: 'Dr. Priya provided exceptional postpartum physical therapy at home.', user: 'Lakshmi Narayanan' },
    ],
  },
  {
    id: 'th-9',
    slug: 'dr-hardik-shah',
    name: 'Dr. Hardik Shah, PT',
    qualification: 'MPT (Neurology & Geriatrics)',
    specialization: 'Neurology',
    experience: '10 Years',
    city: 'Ahmedabad',
    state: 'Gujarat',
    areas: ['SG Highway', 'Prahlad Nagar', 'Bodakdev', 'Satellite', 'Vastrapur', 'Thaltej'],
    rating: 4.8,
    reviewCount: 89,
    imageUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
    languages: ['English', 'Gujarati', 'Hindi'],
    services: ['Neuro Rehabilitation', 'Gait & Balance Training', 'Geriatric Rehab', 'Paralysis Therapy'],
    bio: 'Clinical neuro-physiotherapist specializing in neurological condition management, post-paralysis functional mobility, and geriatric strength training.',
    isVerified: true,
    education: ['MPT (Neurology) - Gujarat University'],
    feedback: [
      { rating: 5, comment: 'Helped my uncle regain balance and walk independently after his neurological event.', user: 'Bhavin Patel' },
    ],
  },
];
